### ISSUE TITLE
ModuleNotFoundError: No module named 'mmgpt.src'

### ISSUE THREAD

**Issue by Sunwood-ai-labs** [OpenMOSS/AnyGPT#9]
There is an error below.

```bash
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
2024-03-26 10:15:35.821675: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-26 10:15:35.821777: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-26 10:15:35.952168: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-26 10:15:38.385135: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/AnyGPT/anygpt/src/infer/cli_infer_base_model.py", line 24, in <module>
    from infer.pre_post_process import extract_text_between_tags
  File "/content/AnyGPT/./anygpt/src/infer/pre_post_process.py", line 7, in <module>
    from mmgpt.src.m_utils.prompter_mmgpt import Prompter
ModuleNotFoundError: No module named 'mmgpt.src'
```

It occurs in Google Colab below

https://colab.research.google.com/drive/13_gZPIRG6ShkAbI76-hC_etvfGhry0DZ?usp=sharing

**Comment by JunZhan2000** [comment]
Thank you for your reminder. The issue has been fixed, and you can try the latest code. If there are any problems, please feel free to contact us.
